### PR TITLE
Don't assume data is ASCII

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by sglyon** [comment]
Good work!

**Comment by lobingera** [comment]
while i agree on the filename, data should be Uint8 still, according to the API
https://developer.gnome.org/rsvg/2.40/RsvgHandle.html#rsvg-handle-new-from-data

**Comment by lobingera** [comment]
... and i see gchar  is also C char ...

**Comment by malmaud** [comment]
Not sure I understand your point - I didnt change the fact that data is a byte array, but rather changed it so you are passing the length of the data in bytes instead of the number of unicode codepoints.

**Comment by lobingera** [comment]
sorry, it was too early in the morning...
I'm always struggling with String and Char definitions in julia but taking the librsvg API (and the GLib definitions into account) i think you are more correct than i was.

**Comment by malmaud** [comment]
Np

**Pull request merged**
