### PR TITLE
Simplify CI config

### PR DESCRIPTION
**Pull request by davidanthoff**
This slightly simplifies and follows standard CI config.

Mainly, though, I just want to trigger a build and see how we are doing :)

### CODE REVIEW

**Comment by lobingera** [comment]
To make a longer story short: We failed on 0.7/1.0 OSX for Cairo homebrew issues. You can follow the discussion here: https://github.com/JuliaGraphics/Cairo.jl/pull/250

**Comment by davidanthoff** [comment]
Can we merge this PR, and then tag a release? That would lead to a strictly better situation than what we have now: we would then have a working 0.7/1.0 version for Win and Linux, and we wouldn't break anything that works right now.

It would help me to move forward with the whole VegaLite.jl compat work for 0.7/1.0.

**Comment by davidanthoff** [comment]
Actually, Windows on 1.0 is also not working, probably needs https://github.com/JuliaPackaging/WinRPM.jl/pull/158. But I think we could still merge this PR and tag a release, at least things would work on 0.7... And once the WinRPM situation is solved, it should just start working on 1.0 as well.

**Comment by lobingera** [comment]
@davidanthoff I made recently some experiences with releasing something that was not available on all platforms and if we do that now for Rsvg i guess i can count the minutes before the first issues arrive. If testing is positive on 2 of 3 platforms for 1.0 i'd do a release. Solving homebrew for Cairo seems to be not far away.

**Pull request merged**
