### PR TITLE
Add OS X build support via home-brew

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by lobingera** [comment]
interesting ... i wasn't aware that anyone except myself is using this ...
As i do not have OSX locally available, but the test pass, i merge.

**Comment by sglyon** [comment]
Thanks!

It took a bit of work to get `librsvg` setup with `Homebrew.jl`, but things are working smoothly

**Comment by lobingera** [comment]
in which context do you use it? Just display of svg?

**Comment by sglyon** [comment]
Quick question, has this been registered on metadata?

If not, do you mind registering it?

**Comment by sglyon** [comment]
Nope, I'm actually using it to write an svg out as a pdf or png: https://github.com/spencerlyon2/PlotlyJS.jl/blob/sl/syncplots/src/savefig.jl#L105-L149

**Comment by lobingera** [comment]
To put it on metadata i see a little bit both code and documentation quality missing. But it's a reasonable target. Let's see if (and when) i can spend the time.

**Comment by lobingera** [comment]
btw: i tried on the last weekend to publish/register but had github problems (i.e. https://github.com/JuliaLang/julia/issues/15381)

**Comment by sglyon** [comment]
I can rarely get Pkg.publish to work. 

Have you tried pushing the created commits directly from the Metadata clone on your machine to your fork of metadata?

**Comment by lobingera** [comment]
yes, it's on my metadata clone (1 commit tag, 1 commit package)
https://github.com/lobingera/METADATA.jl/commit/448323884cba747937237b65c649f73aa80fd163

**Comment by sglyon** [comment]
Excellent. Can you make a PR from your clone manually on github?

That's almost always what I have to do when I tag a new release

// Spencer

**Comment by lobingera** [comment]
I had planning that, but there were are other activities (like working...) that stopped me from doing this...

**Pull request merged**
