### PR TITLE
Seems to be a typo (not sure..)

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by sglyon** [comment]
👍

**Comment by PallHaraldsson** [comment]
This is a "redirect" ("This page redirects to page "Projects/LibRsvg") except it doesn't.., should it go straight to:

https://wiki.gnome.org/action/show/Projects/LibRsvg?action=show&redirect=LibRsvg

**Comment by lobingera** [comment]
is a typo.

**Comment by lobingera** [comment]
@PallHaraldsson 
Looking at the more closely, using this:
https://wiki.gnome.org/Projects/LibRsvg
might be the more appropriate (gnome wiki btw: is terribly unstable, a lot of my bookmarks only work half of the time...)

**Pull request merged**
