### PR TITLE
Move to Project.toml

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
It would be great if we could merge this soon and then tag a new release with the whole new Registrator infrastructure because right now the existing Rsvg tagged versions are all holding back Cairo 0.6.0 from being installed. The logic for that seems flawed to me, but it is what it is (for some reason the migration script from METADATA to General interpreted the "no bounds on Cairo" in the REQUIRE file as "compatible _only_ with versions of Cairo that existed when the migration script ran). I think the easiest way around all of that is to just tag a new release of Rsvg that explicitly doesn't have bounds on Cairo in the Project.toml, i.e this PR here.

**Comment by davidanthoff** [comment]
Hm, don't really understand what is going wrong on Windows, that we need to fix first, obviously.

**Comment by lobingera** [comment]
@davidanthoff Thank's for your work on that. If you are a windows user (i'm not), please run this locally and see if testing passes. This (again) looks like an WinRPM/BinDeps interaction and the strangest thing is, that libgio seems to be downloaded successfully and then not recognized as dependency. btw: if you see strange behaviour with "The logic for that seems flawed to me," don't hesitate to inform the team.

**Comment by davidanthoff** [comment]
Alright, the Windows bug was a stupid mistake on my end (I had accidentally deleted some important lines from build.jl). Now all fixed, all tests pass and this should be ready for merging.

**Comment by lobingera** [comment]
It's not (really) a mistake by you, the BinDeps logic is complicated and not documented at large ...
And actually one could see libgio installed with librsvg - as it is a dependency on the system package management but BinDeps chooses not to recognize it.

**Comment by lobingera** [comment]
So following the logic of the registrator, one issue to register the new version is needed?

**Comment by davidanthoff** [comment]
I think to register a new version you need to install https://github.com/JuliaComputing/Registrator.jl for this repo. I would also suggest to add https://github.com/christopher-dG/tag-bot as well, the combination of the two makes the workflow a bit smoother.

And then you can just comment on the git commit here in github that you want to have tagged, no need to open an issue. But I think an issue would also be fine, either seem to work.

But things are less urgent now, with [this](https://github.com/JuliaRegistries/General/pull/373) PR, the currently registered Rsvg version should also work with Cairo 0.6.

**Pull request merged**
