### PR TITLE
Add librsvg-2-2 as bindeps alias for winrpm

### PR DESCRIPTION
**Pull request by sglyon**
See #4

### CODE REVIEW

**Comment by lobingera** [comment]
I forgot! I did it locally, but didn't push...

**Comment by sglyon** [comment]
No problem.

 I think we should be good to go on all 3 platforms, right?

**Comment by lobingera** [comment]
i'm a little bit waiting for the http://pkg.julialang.org/pulse.html

**Comment by sglyon** [comment]
Sorry, I didn't follow. What are you waiting for?

**Comment by lobingera** [comment]
the julia package pulse is doing testing registered packages in 0.3/0.4/0.5. Unfortunately this is not run regularly.

**Pull request merged**
