### PR TITLE
Update years in LICENSE.md

### PR DESCRIPTION
**Pull request by davidanthoff**
Really I just want to trigger a build. WinRPM.jl is supposed to work on 1.0 now, so fingers crossed this will help with our success rate here.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Alright, getting closer. Now the only thing that doesn't work is 0.7/1.0 on Mac, everything else works, i.e. Windows now passes.

I am actually surprised that things work on Mac on 0.6, but not on 0.7/1.0. I thought the issue with Homebrew.jl was a general homebrew issue, not a 0.7/1.0 specific one?

Do you think we could cut a release with the current state? Or do we have to wait until the Mac situation is resolved? I'm just really worried that that will take forever, and would really like to move forward at least on the platforms that do work currently.

**Comment by lobingera** [comment]
Cairo passes on master, this contains a fix/workaround for the homebrew issue which is a missing dependency in the homebrew environment itself (Cairo -> pangocairo -> harfbuzz -> graphite2). Tony Kelman proposed to solve this problem on the homebrew side and not on the julia side and i agree. As i don't have a computer with OSX for debugging/testing this taking some time.
But if complaints about OSX show up, one can point to Cairo#master.

https://github.com/lobingera/Rsvg.jl/releases/tag/v0.2.2

**Comment by davidanthoff** [comment]
Yay! Thanks so much for keeping at all these build issues, I really, really appreciate it!

**Comment by lobingera** [comment]
change was added manually in #27

**Pull request closed without merging**
