### PR TITLE
Enable precompilation

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by lobingera** [comment]
This might take longer, as i need to track down, why tests are failing (and i'm not near my development box right now). Would it be OK to focus on v0.6/0.7 only? Supporting a mix with v0.5 is hard nowadays.

**Comment by sglyon** [comment]
Yeah for sure -- I have also given up directly trying to support 0.5 still ("if it works, great, if not I don't have the extra capacity to make it work")

**Comment by lobingera** [comment]
This is manually included in https://github.com/lobingera/Rsvg.jl/pull/14 which looks promising, as the 0.6 tests pass. I'll close this.

**Comment by sglyon** [comment]
Sounds great, thanks!

**Comment by lobingera** [comment]
It's now on master, testing on travis (OSX) seems to be delayed. If that's through, i'll tag.

**Pull request closed without merging**
