### PR TITLE
Julia 0.7

### PR DESCRIPTION
**Pull request by davidanthoff**
This is not ready, but it does make everything pass on julia 0.7 for me.

Main question for @lobingera: are you ok to drop julia 0.6 support? That would make things a lot easier here, as I am not sure how to handle all the compat issues if we want to make things work on 0.6 and 0.7...

### CODE REVIEW

**Comment by lobingera** [comment]
As long as there is no official and stable 0.7, dropping the 0.6 support is a little bit unfriendly to the community ...
I can take a look later today, for simple library adaptations (mostly structure and ccalls) 0.6 support isn't that complicated (see Cairo...).

**Comment by davidanthoff** [comment]
At least in theory it should now work on julia 0.6 & 0.7. Lets see what CI says.

**Comment by lobingera** [comment]
@davidanthoff 1 out of 6 isn't that successful, the failing 0.6 on MacOSX seems to be (again) https://github.com/JuliaGraphics/Cairo.jl/issues/230

**Comment by davidanthoff** [comment]
I think these are all problems with upstream packages like WinRPM and Homebrew... The travis 0.7 builds all seem to crash with something WinRPM and Homebrew related. I'm also seeing Homebrew errors on the appveyor build...

So we might just have to wait with this PR until these things get fixed in WinRPM and Homebrew...

**Comment by lobingera** [comment]
I agree. The next weeks i should have more time to spend on this anyway. The BinDeps problem is really a setback

**Pull request merged**
