### PR TITLE
Migrate to BinaryProvider.jl

### LINKED ISSUE #19: InitError: error compiling __init__: could not load library "~\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\librsvg-2-2.DLL" The specified module could not be found.
Hi,

I have this wired error during init of module Rsvg for a quiet long time on a specific windows 7 machine, I tried update windows, delete and reinstall Julia packages, including Gtk.jl and Cairo.jl, but still not working. On the other hand, the other windows 7 machine works fine without this error.

I have no idea how this come, maybe some system configuration?

I am running Julia 0.6.3, and Rsvg.jl is v0.2.1

### LINKED ISSUE #23: Error on MacOS, Julia 1.0
```
(v1.0) pkg> add Rsvg
 Resolving package versions...
 Installed Rsvg ─ v0.2.1
  Updating `Project.toml`
  [c4c386cf] + Rsvg v0.2.1
  Updating `Manifest.toml`
  [c4c386cf] + Rsvg v0.2.1
  Building Rsvg → `~/.julia/packages/Rsvg/AEdKr/deps/build.log`
┌ Error: Error building `Rsvg`:
│ ERROR: LoadError: LoadError: UndefVarError: is_linux not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] eval at ./boot.jl:319 [inlined]
│  [3] @static(::LineNumberNode, ::Module, ::Any) at ./osutils.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:388
│  [8] top-level scope at none:0
│ in expression starting at /Users/abmlab/.julia/packages/Rsvg/AEdKr/deps/build.jl:8
│ in expression starting at /Users/abmlab/.julia/packages/Rsvg/AEdKr/deps/build.jl:8
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

### LINKED ISSUE #29: double homebrew linking
I cannot use both Gadfly and VegaLite for plotting because of a strange issue that I think comes from `Rsvg.jl`, but it's maybe also related to `Homebrew.jl` (@staticfloat)?

The installation runs fine (I tried reinstalling everything, from scratch, checkout master etc.), but testing `Rsvg.jl` always gives the following error:

    objc[47481]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x111399498) and /Users/ken/.julia/packages/Homebrew/s09IX/deps/usr/lib/libgio-2.0.dylib (0x129254498). One of the two will be used. Which one is undefined.

I tried linking inside julia package folders manually to system `libgio` (installed through brew on my system), but although the errors go away, the plots are all scrambled.

Any help appreciated, thanks!

<details>
<summary>Full output</summary>

```
(v1.0) pkg> test Rsvg
   Testing Rsvg
    Status `/var/folders/h9/8wp6_1kx6_v6wm7_vy5w_pbm0000gn/T/tmp1eCjdp/Manifest.toml`
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [e1450e63] BufferedStreams v1.0.0
  [159f3aea] Cairo v0.5.6
  [3da002f7] ColorTypes v0.7.5
  [5ae59095] Colors v0.9.5
  [34da2185] Compat v1.5.1
  [53c48c17] FixedPointNumbers v0.5.3
  [a2bd30eb] Graphics v0.4.0
  [0862f596] HTTPClient v0.2.1
  [d9be37ee] Homebrew v0.7.1
  [682c06a0] JSON v0.20.0
  [b27032c2] LibCURL v0.4.1
  [522f3ed2] LibExpat v0.5.0
  [2ec943e9] Libz v1.0.0
  [77ba4419] NaNMath v0.3.2
  [189a3867] Reexport v0.2.0
  [c4c386cf] Rsvg v0.2.3+ #master (https://github.com/lobingera/Rsvg.jl.git)
  [30578b45] URIParser v0.4.0
  [c17dfb99] WinRPM v0.4.2
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
Test Summary:                | Pass  Total
dimensions of known images   |    8      8
Test Summary:                | Pass  Total
render to png                |    4      4
objc[47481]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x111399498) and /Users/ken/.julia/packages/Homebrew/s09IX/deps/usr/lib/libgio-2.0.dylib (0x129254498). One of the two will be used. Which one is undefined.

(process:47481): librsvg-CRITICAL **: 22:12:27.907: rsvg_handle_new_from_stream_sync: assertion 'G_IS_INPUT_STREAM (input_stream)' failed

signal (11): Segmentation fault: 11
in expression starting at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:60
getproperty at ./sysimg.jl:18 [inlined]
getindex at ./refvalue.jl:32 [inlined]
handle_new_from_data at /Users/ken/.julia/packages/Rsvg/uwc9D/src/calls.jl:109
test_render_string_to_png at /Users/ken/.julia/packages/Rsvg/uwc9D/test/test.jl:52
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
test_render_string_to_png at /Users/ken/.julia/packages/Rsvg/uwc9D/test/test.jl:49
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
macro expansion at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:63 [inlined]
macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
top-level scope at /Users/ken/.julia/packages/Rsvg/uwc9D/test/runtests.jl:62
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:799
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:838
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:839 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:846
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29
include at ./client.jl:392
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1831
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:682
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x10a72fc0f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:805
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:754
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:622
eval at ./boot.jl:319
exec_options at ./client.jl:243
_start at ./client.jl:425
true_main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 5877126 (Pool: 5876152; Big: 974); GC: 12
ERROR: Package Rsvg errored during testing

julia> versioninfo(verbose=true)
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  uname: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz:
              speed         user         nice          sys         idle          irq
       #1  2800 MHz      83706 s          0 s      68444 s     577018 s          0 s
       #2  2800 MHz       4185 s          0 s       3715 s     721189 s          0 s
       #3  2800 MHz      88050 s          0 s      35528 s     605526 s          0 s
       #4  2800 MHz       4511 s          0 s       3665 s     720909 s          0 s
       #5  2800 MHz      74952 s          0 s      25474 s     628670 s          0 s
       #6  2800 MHz       4765 s          0 s       3308 s     721009 s          0 s
       #7  2800 MHz      63477 s          0 s      19159 s     646455 s          0 s
       #8  2800 MHz       4920 s          0 s       2895 s     721264 s          0 s

  Memory: 16.0 GB (441.94921875 MB free)
  Uptime: 258904.0 sec
  Load Avg:  1.4580078125  1.60009765625  1.673828125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  XPC_FLAGS = 0x0
  PATH = /usr/local/sbin:/Users/ken/anaconda3/bin:/Users/ken/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
  TERM = xterm-256color
  HOME = /Users/ken

julia>
```

</details>

### LINKED ISSUE #31: Error: Error building `Rsvg`
Julia Version 1.0.3
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4

┌ Error: Error building `Rsvg`: 
│ ERROR: LoadError: None of the selected providers can install dependency rsvg.
│ Use BinDeps.debug(package_name) to see available providers
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [4] top-level scope at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /home/cllcentosvm/.julia/packages/Rsvg/uwc9D/deps/build.jl:33
└ @ Pkg.Operations /home/conda/feedstock_root/build_artifacts/julia_1548684429855/work/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

### LINKED ISSUE #34: Error building Rsvg
I receive the following error when trying to build Rsvg.jl on Julia 1.1.0 on a Macbook pro running High Sierra 10.13.6. Can you help me solve this? We're in the final stage of a development project so it's rather urgent.

The error I receive is:

> ERROR: LoadError: LoadError: LoadError: Unable to load 
> 
> librsvg (/Users/George/.julia/packages/Homebrew/s09IX/deps/usr/lib/librsvg-2.2.dylib)
> 
> Please re-run Pkg.build(package), and restart Julia.
> Stacktrace:
>  [1] error(::String, ::String) at ./error.jl:42
>  [2] @checked_lib(::LineNumberNode, ::Module, ::Any, ::Any) at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:11
>  [3] include at ./boot.jl:326 [inlined]
>  [4] include_relative(::Module, ::String) at ./loading.jl:1038
>  [5] include at ./sysimg.jl:29 [inlined]
>  [6] include(::String) at /Users/George/.julia/packages/Rsvg/uwc9D/src/Rsvg.jl:2
>  [7] top-level scope at none:0
>  [8] include at ./boot.jl:326 [inlined]
>  [9] include_relative(::Module, ::String) at ./loading.jl:1038
>  [10] include(::Module, ::String) at ./sysimg.jl:29
>  [11] top-level scope at none:2
>  [12] eval at ./boot.jl:328 [inlined]
>  [13] eval(::Expr) at ./client.jl:404
>  [14] top-level scope at ./none:3
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:21
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:21
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/src/Rsvg.jl:5
> ERROR: LoadError: Failed to precompile Rsvg [c4c386cf-5103-5370-be45-f3a111cca3b8] to /Users/George/.julia/compiled/v1.1/Rsvg/aWLhH.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
>  [3] _require(::Base.PkgId) at ./loading.jl:960
>  [4] require(::Base.PkgId) at ./loading.jl:858
>  [5] require(::Module, ::Symbol) at ./loading.jl:853
>  [6] include at ./boot.jl:326 [inlined]
>  [7] include_relative(::Module, ::String) at ./loading.jl:1038
>  [8] include(::Module, ::String) at ./sysimg.jl:29
>  [9] top-level scope at none:2
>  [10] eval at ./boot.jl:328 [inlined]
>  [11] eval(::Expr) at ./client.jl:404
>  [12] top-level scope at ./none:3
> in expression starting at /Users/George/.julia/packages/VariantVisualization/cbN7w/src/VariantVisualization.jl:6
>

### PR DESCRIPTION
**Pull request by davidanthoff**
~~Not yet functional.~~ I think now ready, but lets wait for CI runs.

I'm also going to declare that this PR fixes all the deployment problems related to BinDeps.jl:

Fixes #19, fixes #23, fixes #29, fixes #31, fixes #34.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@staticfloat and @giordano, I've tried to use the new binaries hosted [here](https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases).

What I did is essentially just copy the whole Cairo.jl `build.jl` script, and then tried to add the rsvg specific stuff. When I run the build, I get an error
```
ERROR: LoadError: LoadError: LibraryProduct(nothing, ["librsvg"], :librsvg,
Prefix(C:\\Users\\david\\.julia\\dev\\Rsvg\\deps\\usr)") is not satisfied, cannot generate deps.jl!
```
If I then look into the folder `deps/usr/bin`, I see a `librsvg-2-2.dll` there (and lots of other shared libraries as well). When I try to load that directly with:
```
julia> using Libdl
julia> dlopen("librsvg-2-2")
ERROR: could not load library "librsvg-2-2"
The specified module could not be found.
```
It is not clear to me what that means. That there is some other dll missing that `librsvg-2-2` depends on? If that, is there some way that I can get the name of that lib? Or something entirely different?

**Comment by giordano** [comment]
Some remarks:

* to get more information during installation, I recommend setting `const verbose = true` at the beginning of the `build*.jl` files (but I don't expect much more information in this case)
* the order with which you open the libraries in `build.jl` matters (but in your case looks fine)
* these are the libraries `librsvg-2-2.dll` links to
  ```
  % objdump -p bin/librsvg-2-2.dll|grep DLL
          DLL
   vma:            Hint    Time      Forward  DLL       First
          DLL Name: ADVAPI32.dll
          DLL Name: KERNEL32.dll
          DLL Name: msvcrt.dll
          DLL Name: libcairo-2.dll
          DLL Name: libcroco-0.6-3.dll
          DLL Name: libfontconfig-1.dll
          DLL Name: libgdk_pixbuf-2.0-0.dll
          DLL Name: libgio-2.0-0.dll
          DLL Name: libglib-2.0-0.dll
          DLL Name: libgobject-2.0-0.dll
          DLL Name: libpango-1.0-0.dll
          DLL Name: libpangocairo-1.0-0.dll
          DLL Name: libpangoft2-1.0-0.dll
          DLL Name: libxml2-2.dll
  ```
  You can check with `Libdl.dllist()` which libraries have been already opened
* We went through a few iterations of `Cairo`, also after the release of the binaries for `Cairo.jl`: https://github.com/JuliaPackaging/Yggdrasil/commits/master/C/Cairo/build_tarballs.jl.  I'm not sure which version was used to build `libRSVG`, but maybe this is not important
* I think you need `libcroco`: https://github.com/JuliaPackaging/Yggdrasil/blob/bf4ac37978764a3e953d06d7ed052ef06968f3bf/R/LibRSVG/build_tarballs.jl.  And `libcroco` needs `XML2`.  Here are the build scripts: https://gist.github.com/giordano/78fd43b1b3626c9bc837b900f29c4f0b.  `XML2` depends on `zlib`, `libcroco` depends on `XML2` and `Glib`, this is important for order with which you open them.

**Comment by davidanthoff** [comment]
Ah, very helpful! So I now added `libcroco` and `XML2`. But when I run the build script and then just look at the dlls in the `usr/bin` folder and then compare that to the list you posted above, then the following files are not there:
```
libfontconfig-1.dll
libgdk_pixbuf-2.0-0.dll
libpangoft2-1.0-0.dll
```
I think I managed to add `libfontconfig` on windows now. But then that still leaves the other two, I guess? Any idea where I might get those from?

**Comment by davidanthoff** [comment]
I'd say that if this passes CI we can merge.

There are still some things we might want to do in further PRs before we tag:
- Enable drone and cirrus testing for other binary platforms, like in Cairo.jl
- Enable coverage reporting for the repo, I would suggest by enabling https://codecov.io/ for this repo and then switching that flag on in travis.

Thanks to @giordano and @staticfloat for getting us to this state in the first place :)

**Comment by giordano** [comment]
I can add CI scripts for Drone (Linux on ARM and ARM64) and Cirrus (FreeBSD), too :slightly_smiling_face:

**Comment by davidanthoff** [comment]
So Windows 32 bit on julia 0.7 fails... My vote would be to just drop julia 0.7 support at this point, I don't think it is worth the effort to support that platform anymore. @lobingera, would you be ok with that?

**Comment by giordano** [comment]
I think also Cairo has problems on that platform

**Comment by davidanthoff** [comment]
Ok, I think this can be merged at this point.

The appveyor failure isn't really an issue because it is only julia 0.7 32 bit, and then I would suggest we remove appveyor in any case now that travis covers windows builds as well.

**Comment by davidanthoff** [comment]
Bump, can we merge this and tag a new release?

**Comment by lobingera** [comment]
Let's see.

**Comment by davidanthoff** [comment]
Great, thanks! So tests also pass on `master`, so I think this is ready to tag a new release? I think this should become 0.3.0, right?

**Pull request merged**
